In [1]:
matrix = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

In [2]:
[[i + 1 for i in row]for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [3]:
# 首先导入NumPy
import numpy as np

In [4]:
# 使用列表构造一个一维数组
array1 = np.array([10, 100, 1000.])

In [5]:
#使用嵌套列表构造一个二维数组
array2 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])

In [6]:
array1.dtype

dtype('float64')

In [7]:
float(array1[0])

10.0

In [8]:
array2 + 1

array([[2., 3., 4.],
       [5., 6., 7.]])

In [9]:
array2 * array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [10]:
array2 * array1

array([[  10.,  200., 3000.],
       [  40.,  500., 6000.]])

In [11]:
array2 @ array2.T  # array2.T是array2.transpose()的缩写

array([[14., 32.],
       [32., 77.]])

In [12]:
import math  # math.sqrt()计算平方根

In [13]:
math.sqrt(array2)  # 这里会发生错误

TypeError: only size-1 arrays can be converted to Python scalars

In [14]:
np.array([[math.sqrt(i) for i in row]for row in array2])

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [15]:
np.sqrt(array2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [16]:
array2.sum(axis=0)  # 返回一维数组 【axis=0表示沿着列求和，即将每一列的元素相加，而axis=1表示沿着行求和，即将每一行的元素相加。】

array([5., 7., 9.])

In [17]:
array2.sum()

21.0

In [18]:
array1[2]  # 返回标量

1000.0

In [19]:
array2[0, 0]  # 返回标量

1.0

In [20]:
array2[:, 1:]  # 返回二维数组

array([[2., 3.],
       [5., 6.]])

In [21]:
array2[:, 1] # 返回一维数组

array([2., 5.])

In [22]:
array2[1, :2] # 返回一维数组

array([4., 5.])

In [23]:
np.arange(2 * 5).reshape(2, 5)  # 2行，5列 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
np.random.randn(2, 3)  # 2行 ，3列

array([[ 0.30110013, -0.23061352, -0.32277882],
       [ 0.12448525, -2.82624661,  1.55372353]])

In [25]:
array2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
# 在对NumPy数组进行切片时，其返回值是视图即意味着：
    # 是在操作原数组的一个子集，而没有发生数据的复制。因而设置视图的值也会改变原数组中的值
# 如果不想要这样的结果，即更改【26】代码
# subset = array2[:, :2].copy()

In [26]:
subset = array2[:,: 2]
subset

array([[1., 2.],
       [4., 5.]])

In [27]:
subset[0, 0] = 1000
subset

array([[1000.,    2.],
       [   4.,    5.]])

In [28]:
array2

array([[1000.,    2.,    3.],
       [   4.,    5.,    6.]])